version: 1.0.{build}
image:
- Visual Studio 2015
clone_depth: 1

<<<<<<< HEAD
artifacts:
- path: nlp_windows-$(appveyor_repo_tag_name).zip
=======
>>>>>>> travis
skip_non_tags: false
platform: x64

build_script:
- cmd: >-

    build\buildscript.bat

    build\test.bat

<<<<<<< HEAD
after_build:
- cmd: >-
    build\package.bat

deploy:
 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
=======
>>>>>>> travis
